kind: Deployment
apiVersion: apps/v1
metadata:
  name: '{{ meta.name }}-mcrouter'
  namespace: '{{ meta.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcrouter
  template:
    metadata:
      labels:
        app: mcrouter
    spec:
      containers:
      - name: mcrouter
        command:
          - mcrouter
        args:
          - -f
          - /app/config.json
          - --validate-config=run 
          - -p 
          - "{{ mcrouter_port }}"
{% if debug_fifo_root != '' %}
          - --debug-fifo-root={{ debug_fifo_root }}
{% endif %}
        image: '{{ mcrouter_image }}'
        ports:
          - containerPort: {{ mcrouter_port }}
        volumeMounts:
          - mountPath: /app 
            name: mcrouter-config-volume 
{% if image_pull_secrets != '' %}
      imagePullSecrets:
        - name: {{ image_pull_secrets }}
{%  endif %}
        volumes:
          - name: mcrouter-config-volume 
            configMap:
              name: mcrouter-config
              optional: false
              
