# permissions for end users to view mcrouters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcrouter-viewer-role
rules:
- apiGroups:
  - cache.targetkiranp
  resources:
  - mcrouters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.targetkiranp
  resources:
  - mcrouters/status
  verbs:
  - get
