# permissions for end users to edit mcrouters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcrouter-editor-role
rules:
- apiGroups:
  - cache.targetkiranp
  resources:
  - mcrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.targetkiranp
  resources:
  - mcrouters/status
  verbs:
  - get
